Instagram post image operator
Tauffer-Consulting/flowui_example_operators_repository pull request #4
Opened 2022-11-16 14:11 UTC by giupb

2022-11-16 14:27 UTC, vinicvaz requested changes
Good work @giupb !
I did a few reviews that we can discuss about and when it is done I think we can merge it and release a new version to test in flowui

2022-11-16 14:27 UTC, vinicvaz commented on operators/InstaImagePostOperator/operator.py
> +import requests, json, typing, urllib.parse
Remove unused imports
```suggestion
import requests, json, urllib.parse
```

2022-11-16 14:27 UTC, vinicvaz commented on operators/InstaImagePostOperator/operator.py
> +endpoint_base_path = host_domain + graph_api_version + '/'
When concatenating strings is better to use `format string` instead of `+`.
If your string is a url you could consider using a package such as the already imported `urllib`.
Maybe `urllib.parse.urljoin` method should be enough for this case.

2022-11-16 14:27 UTC, vinicvaz commented on operators/InstaImagePostOperator/operator.py
> +    return response['json_content']['id']
We can place all these methods as `static`, `class` or `instance` methods of the `InstaImagePostOperator` class.
Also, the global variables
```
host_domain = 'https://graph.facebook.com/'
graph_api_version = 'v15.0'
endpoint_base_path = host_domain + graph_api_version + '/'
```
Can be defined as class variables.

Also, using these methods inside the `InstaImagePostOperator` allow us to access the **logger** from the `BaseOperator`, so we can replace the `prints` with `self.logger.METHOD`

2022-11-16 14:27 UTC, vinicvaz commented on operators/InstaImagePostOperator/operator.py
> +    endpoint_query_params = f'grant_type=fb_exchange_token&client_id={app_id}&client_secret={app_secret}&fb_exchange_token={access_token}'
Same of the above comment about string/url concatenation

2022-11-16 14:27 UTC, vinicvaz commented on operators/InstaImagePostOperator/operator.py
> +    endpoint_query_params = f'access_token={access_token}'
Same

2022-11-16 14:27 UTC, vinicvaz commented on operators/InstaImagePostOperator/operator.py
> +    endpoint_query_params = f'access_token={access_token}&fields=instagram_business_account'
same

2022-11-16 14:27 UTC, vinicvaz commented on operators/InstaImagePostOperator/operator.py
> +    endpoint_query_params = f'image_url={image_url}&caption={caption}&access_token={access_token}'
same

2022-11-16 19:07 UTC, giupb commented on operators/InstaImagePostOperator/models.py
> +    facebook_page_name: str = Field(
I can only get the Instagram Account ID with the Facebook Page ID. And I can only get the Facebook Page ID with the Facebook Page Name. Notice the parameters of `get_instagram_business_account(access_token:str, page_id:str)`. The `page_id` refers to the Facebook Page ID that I got with `get_page_id(access_token:str, facebook_page_name:str)` that needs the `facebook_page_name`.

2022-11-17 22:17 UTC, giupb commented on operators/InstaImagePostOperator/operator.py
> +    @staticmethod
@vinicvaz I converted all functions to static methods. What do you think?

2023-04-27 11:27 UTC, closed without merging